name: FreeRDP Fork Build

on: [workflow_dispatch]

jobs:
  FreeRDP-build-actions:
    runs-on: windows-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The repository has been cloned to the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      - name: Test msbuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64 
      - run: msbuild /version
      - name: Prepare environment for NMAKE/MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Start Build
        run: pwsh ./setup.ps1
        working-directory: ${{ github.workspace }}/winscripts
      - name: Release
        working-directory: ${{ github.workspace }}/winscripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run:
          pwsh.exe ./github-release.ps1
      - run: echo "This job's status is ${{ job.status }}."
